export const chatActions = {
  GET_USER_CHATS_SAGA: "GET_USER_CHATS_SAGA",
  GET_MESSAGES_SAGA: "GET_MESSAGES_SAGA",
  SEND_MESSAGE_SAGA: "SEND_MESSAGE_SAGA",
  CREATE_NEW_CHAT_SAGA: "CREATE_NEW_CHAT_SAGA",
  GET_ONLINE_USERS_SAGA: "GET_ONLINE_USERS_SAGA",
  GET_CHATS_SAGA: "GET_CHATS_SAGA",
};
