export const userActions = {
  CHECK_USER_SAGA: "CHECK_USER_SAGA",
  REGISTER_EMAIL_USER_SAGA: "REGISTER_EMAIL_USER_SAGA",
  LOGIN_EMAIL_USER_SAGA: "LOGIN_EMAIL_USER_SAGA",
  LOGOUT_USER_SAGA: "LOGOUT_USER_SAGA",
  LOGIN_USER_SAGA: "LOGIN_USER_SAGA",
  UPDATE_USER_SAGA: "UPDATE_USER_SAGA",
};
